* fixed broken nextmap.

diff --git a/_2_build_and_install-debug b/_2_build_and_install-debug
--- a/_2_build_and_install-debug
+++ b/_2_build_and_install-debug
@@ -7,3 +7,10 @@ mkdir -p ${INSTALLPATH}
 ./configure --prefix=${INSTALLPATH} 1>log.txt 2>err.txt && \
 make                                1>log.txt 2>err.txt && \
 make install                        1>log.txt 2>err.txt
+
+if [ "$?" = 0 ] ;
+then
+  echo "OK"
+else
+  echo "ERROR while build"
+fi
